---
version: '3'
services:

#
# dynamic dns updater
#
  ddns_client:
    env_file:
      - auth.env
    environment:
      - 'POLL=30'
      - 'CLOUDFLARE_RECORD=frontend'
      - 'CLOUDFLARE_ZONE=tenzin.io'
    build:
      context: ./build-ddns_client 

#
# mkcert
#
  mkcert:
    image: ghcr.io/tenzin-io/mkcert:arm64v8-v1
    environment:
      - 'CERT_HOSTNAME=frontend'
      - 'CERT_DOMAIN=tenzin.io'
    volumes:
      - certs_data:/certs.d/

#
# frontend proxy
#
  nginx:
    build: 
      context: ./build-nginx
    volumes:
      - certs_data:/etc/nginx/certs.d/
    restart: always
    ports:
      - 443:443
    depends_on:
      - mkcert

volumes:
  certs_data:
